name: flutter_analyze

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-11, macos-12]
        flutter-version: [stable, "3.0.5"]

    name: flutter_analyze
    runs-on: ${{ matrix.os }}
    steps:
      - name: set up repository
        uses: actions/checkout@v3
      - name: set up flutter
        uses: subosito/flutter-action@v2.6.1
        with:
          channel: ${{ matrix.os }}
          cache: false
      - name: flutter doctor
        run: flutter doctor -v
      - name: flutter pub get
        run: flutter pub get
      - name: flutter analyze
        run: flutter analyze
